version: '2.1'
services: 
  nocodb: 
    depends_on: 
      union_db: 
        condition: service_healthy
    env_file:
      - .env
    image: "nocodb/nocodb:latest"
    ports: 
      - "3000:8080"
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
  union_db:
    env_file:
      - .env
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres
    restart: always
    volumes: 
      - "db_data:/var/lib/postgresql/data"
volumes: 
  db_data: {}
  nc_data: {}
