version: '2.1'
services:
  union_web:
    build:
      context: './..'
      dockerfile: './docker/web/Dockerfile'
    ports:
      - "3000:3000"
  proxy:
    build:
      context: './proxy'
    depends_on:
      - union_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/var/local
networks:
  proxynet:
    name: union_network